#!/usr/bin/env python
"""A wrapper script around clang-format, suitable for linting multiple files
and to use for continuous integration.

This is just an alternative API for the command line, it produces a diff,
and it returns a sensible exit code.

"""

from __future__ import print_function

import argparse
import difflib
import multiprocessing
import os
import subprocess
import signal
import sys

from functools import partial

DEFAULT_EXTENSIONS = 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'


class ExitStatus:
    SUCCESS = 0
    DIFF = 1
    TROUBLE = 2


def list_files(files, recursive=False, extensions=None):
    out = []
    for file in files:
        if recursive and os.path.isdir(file):
            for dirpath, dnames, fnames in os.walk(file):
                for f in fnames:
                    ext = os.path.splitext(f)[1][1:]
                    if ext in (extensions or []):
                        out.append(os.path.join(dirpath, f))
        else:
            out.append(file)
    return out


def make_diff(file, original, reformatted):
    return list(
        difflib.diff_bytes(
            difflib.unified_diff,
            original,
            reformatted,
            fromfile='{}\t(original)'.format(file).encode('utf-8'),
            tofile='{}\t(reformatted)'.format(file).encode('utf-8'),
            n=3))


class DiffError(Exception):
    def __init__(self, message, errs=None):
        super(DiffError, self).__init__(message)
        self.errs = errs or []


def run_clang_format_diff(args, file):
    try:
        with open(file, "rb") as f:
            original = f.readlines()
    except IOError as exc:
        raise DiffError(str(exc))
    invocation = [args.clang_format_executable, file]
    try:
        proc = subprocess.Popen(
            invocation, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except OSError as exc:
        raise DiffError(str(exc))
    # hopefully the stderr pipe won't get full and block the process
    outs = proc.stdout.readlines()
    errs = proc.stderr.readlines()
    proc.wait()
    if proc.returncode:
        raise DiffError("clang-format exited with status {}: '{}'\n".format(
            proc.returncode, file), errs)
    return make_diff(file, original, outs), errs


def bold_red(s):
    return '\x1b[1m\x1b[31m' + s + '\x1b[0m'


def colorize(diff_lines):
    def bold(s):
        return b'\x1b[1m' + s + b'\x1b[0m'

    def cyan(s):
        return b'\x1b[36m' + s + b'\x1b[0m'

    def green(s):
        return b'\x1b[32m' + s + b'\x1b[0m'

    def red(s):
        return b'\x1b[31m' + s + b'\x1b[0m'

    for line in diff_lines:
        if line[:4] in [b'--- ', b'+++ ']:
            yield bold(line)
        elif line.startswith(b'@@ '):
            yield cyan(line)
        elif line.startswith(b'+'):
            yield green(line)
        elif line.startswith(b'-'):
            yield red(line)
        else:
            yield line


def print_diff(diff_lines, use_color):
    if use_color:
        diff_lines = colorize(diff_lines)
    for line in diff_lines:
        sys.stdout.write(line.decode('utf-8'))


def main():
    parser = argparse.ArgumentParser(
        description='Run clang-format and produce diff of the output.')
    parser.add_argument(
        '--clang-format-executable',
        help='path to the clang-format executable',
        default='clang-format')
    parser.add_argument(
        '--extensions',
        help='comma separated list of file extensions',
        default=DEFAULT_EXTENSIONS)
    parser.add_argument(
        '-r',
        '--recursive',
        action='store_true',
        help='run recursively over directories')
    parser.add_argument('files', metavar='file', nargs='+')
    parser.add_argument(
        '-j',
        metavar='N',
        type=int,
        default=0,
        help='run N clang-format jobs in parallel'
        ' (default number of cpus + 1)')
    parser.add_argument(
        '--color',
        default='auto',
        choices=['auto', 'always', 'never'],
        help='show colored diff (default: auto)')

    args = parser.parse_args()

    # use default signal handling, like diff return SIGINT value on ^C
    # https://bugs.python.org/issue14229#msg156446
    signal.signal(signal.SIGINT, signal.SIG_DFL)

    max_task = args.j
    if max_task == 0:
        max_task = multiprocessing.cpu_count() + 1

    pool = multiprocessing.Pool(max_task)

    colored_stdout = False
    colored_stderr = False
    if args.color == 'always':
        colored_stdout = True
        colored_stderr = True
    elif args.color == 'auto':
        colored_stdout = sys.stdout.isatty()
        colored_stderr = sys.stderr.isatty()

    retcode = ExitStatus.SUCCESS
    files = list_files(
        args.files,
        recursive=args.recursive,
        extensions=args.extensions.split(','))
    it = pool.imap_unordered(partial(run_clang_format_diff, args), files)
    while True:
        try:
            outs, errs = it.next()
        except StopIteration:
            break
        except DiffError as e:
            retcode = ExitStatus.TROUBLE
            prog = sys.argv[0]
            if colored_stderr:
                print("{}: {} {}".format(prog, bold_red("error:"), str(e)))
            else:
                print("{}: error: {}".format(prog, str(e)))
            for line in e.errs:
                sys.stderr.write(line.decode('utf-8'))
        else:
            for line in errs:
                sys.stderr.write(line)
            if outs == []:
                continue
            print_diff(outs, use_color=colored_stdout)
        if retcode == ExitStatus.SUCCESS:
            retcode = ExitStatus.DIFF
    sys.exit(retcode)


if __name__ == '__main__':
    main()
