#!/usr/bin/env python
"""A wrapper script around clang-format, suitable for linting multiple files
and to use for continuous integration.

This is just an alternative API for the command line, it produces a diff,
and it returns a sensible exit code.

"""

import argparse
import difflib
import multiprocessing
import os
import subprocess
import signal
import sys

DEFAULT_EXTENSIONS = 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'


def list_files(files, recursive=False, extensions=None):
    out = []
    for file in files:
        if recursive and os.path.isdir(file):
            for dirpath, dnames, fnames in os.walk(file):
                for f in fnames:
                    ext = os.path.splitext(f)[1][1:]
                    if ext in (extensions or []):
                        out.append(os.path.join(dirpath, f))
        else:
            out.append(file)
    return out


def diff(file, original, reformatted):
    return list(
        difflib.diff_bytes(
            difflib.unified_diff,
            original,
            reformatted,
            fromfile='{}\t(original)'.format(file).encode('utf-8'),
            tofile='{}\t(reformatted)'.format(file).encode('utf-8'),
            n=3))


def run_clang_format_diff(param_pack):
    args, file = param_pack
    invocation = [args.clang_format_executable, file]
    proc = subprocess.Popen(invocation, stdout=subprocess.PIPE)
    reformatted = proc.stdout.readlines()
    proc.wait()
    if proc.returncode:
        return None
    with open(file, "rb") as f:
        original = f.readlines()
    return diff(file, original, reformatted)


def main():
    parser = argparse.ArgumentParser(
        description='Run clang-format and produce diff of the output.')
    parser.add_argument(
        '--clang-format-executable',
        help='path to the clang-format executable',
        default='clang-format')
    parser.add_argument(
        '--extensions',
        help='comma separated list of file extensions',
        default=DEFAULT_EXTENSIONS)
    parser.add_argument(
        '-r',
        '--recursive',
        action='store_true',
        help='run recursively over directories')
    parser.add_argument('files', metavar='file', nargs='+')
    parser.add_argument(
        '-j',
        metavar='N',
        type=int,
        default=0,
        help='run N clang-format jobs in parallel'
        ' (default number of cpus + 1)')

    args = parser.parse_args()

    # use default signal handling, like diff return SIGINT value on ^C
    # https://bugs.python.org/issue14229#msg156446
    signal.signal(signal.SIGINT, signal.SIG_DFL)

    max_task = args.j
    if max_task == 0:
        max_task = multiprocessing.cpu_count() + 1

    pool = multiprocessing.Pool(max_task)

    retcode = 0
    files = list_files(
        args.files,
        recursive=args.recursive,
        extensions=args.extensions.split(','))
    for diff in pool.imap(run_clang_format_diff,
                          zip([args] * len(files), files)):
        if diff == []:
            continue
        for line in (diff or []):
            sys.stdout.write(line.decode('utf-8'))
        retcode = 1

    sys.exit(retcode)


if __name__ == '__main__':
    main()
