#!/bin/bash

# Wrapper to work around `git-clang-format --diff's lack of sensible exit code.
# Run like this:
#     git-clang-format-wrapper git -c color.diff=always clang-format --diff <args...>

set -o errexit
set -o pipefail

temp=$(mktemp --tmpdir git-clang-format-diff.XXXXXX)
trap 'rm "$temp"' EXIT
"$@" | tee "$temp"
if [[ -s "$temp" ]]; then
    exit 1
fi
